from typing import TypedDict
from anthropic.types import ToolParam
from anthropic.types.beta import FileMetadata
from ..chat import client


class FileEntry(TypedDict):
    id: str
    filename: str
    mime_type: str
    size_bytes: int
    created_at: str
    downloadable: bool


class ListFilesResult(TypedDict):
    files: list[FileEntry]


list_files_schema: ToolParam = {
    "name": "list_files",
    "description": (
        "List the files in the workspace — both files uploaded with upload_file "
        "and files generated by code execution. Use this to see what is available, "
        "along with each file's id, name, size, and whether it can be downloaded."
    ),
    "input_schema": {"type": "object", "properties": {}, "required": []},
}


def _to_entry(file: FileMetadata) -> FileEntry:
    return {
        "id": file.id,
        "filename": file.filename,
        "mime_type": file.mime_type,
        "size_bytes": file.size_bytes,
        "created_at": str(file.created_at),
        "downloadable": bool(file.downloadable),
    }


def list_files() -> ListFilesResult:
    return {"files": [_to_entry(file) for file in client.beta.files.list()]}
