[project]
name = "learning-claude"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "anthropic>=0.109.1",
    "claude-agent-sdk>=0.2.99",
    "numpy>=2.5.0",
    "prompt-toolkit>=3.0.52",
    "python-dotenv>=1.2.2",
    "sentence-transformers>=5.6.0",
]
